# This is a basic workflow to help you get started with GitHub Actions

name: Check README

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs on a Windows runner
  check-readme:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a PowerShell script to check if README.md contains the word scolombi
      - name: Check README
        run: |
          $readme = Get-Content README.md
          if ($readme -match "scolombi") {
            Write-Output "README contains scolombi"
          } else {
            Write-Error "README does not contain scolombi"
            exit 1
          }
